# Site settings
title: "Opreker Ganteng"
email: oprekerganteng@gmail.com
description: "Opreker tapi Ganteng"
baseurl: ""
url: "http://ganteng.belajaropensource.or.id"
avatar: "/assets/images/user.png"

sass:
 sass_dir: _sass
 style: compressed
paginate: 5
paginate_path: "blog/page:num/"

# Build settings
markdown: kramdown

